publish-indexes:
  needs: [build, test, deploy]
  runs-on: ubuntu-latest
  container:
    image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-2
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: docs
    - name: Unzip artifact
      run: |
        unzip -O UTF-8 -qq ${{ env.ALGOLIA_ARTIFACT }} -d algolia-indexes
        env algolia-key=${{env.ALGOLIA_KEY}} java -jar /opt/builder/help-publication-agent.jar \
        update-index \
        --application-name ${{env.ALGOLIA_APP_NAME}} \
        --index-name ${{env.ALGOLIA_INDEX_NAME}} \
        --product ${{env.CONFIG_JSON_PRODUCT}} \
        --version ${{env.CONFIG_JSON_VERSION}} \
        --index-directory algolia-indexes/ \
        2>&1 | tee algolia-update-index-log.txt